version: "3"

services:

  runtime-setup:
    image: swift-nio-transport-services:20.04-main
    build:
      args:
        ubuntu_version: "focal"
        base_image: "swiftlang/swift:nightly-main-focal"

  test:
    image: swift-nio-transport-services:20.04-main

  shell:
    image: swift-nio-transport-services:20.04-main
