version: "3"

services:

  runtime-setup:
    image: swift-nio-transport-services:22.04-5.10
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.10"

  documentation-check:
    image: swift-nio-transport-services:22.04-5.10

  test:
    image: swift-nio-transport-services:22.04-5.10

  shell:
    image: swift-nio-transport-services:22.04-5.10
