version: "3"

services:

  runtime-setup:
    image: swift-nio-transport-services:16.04-5.2
    build:
      args:
        ubuntu_version: "xenial"
        swift_version: "5.2"

  test:
    image: swift-nio-transport-services:16.04-5.2

  shell:
    image: swift-nio-transport-services:16.04-5.2
