version: "3"

services:

  runtime-setup:
    image: swift-nio-transport-services:22.04-main
    build:
      args:
        ubuntu_version: "jammy"
        base_image: "swiftlang/swift:nightly-main-jammy"

  documentation-check:
    image: swift-nio-transport-services:22.04-main

  test:
    image: swift-nio-transport-services:22.04-main

  shell:
    image: swift-nio-transport-services:22.04-main
