version: "3"

services:

  runtime-setup:
    image: swift-nio-transport-services:22.04-5.9
    build:
      args:
        ubuntu_version: "jammy"
        base_image: "swiftlang/swift:nightly-5.9-jammy"

  documentation-check:
    image: swift-nio-transport-services:22.04-5.9

  test:
    image: swift-nio-transport-services:22.04-5.9

  shell:
    image: swift-nio-transport-services:22.04-5.9
